### PR TITLE
Add product specific URLs

### PR DESCRIPTION
**Pull request by albedoweb**

### CODE REVIEW

**Comment by rjriel** [comment]
I like this idea, @albedoweb did you want to update node and ruby or let me run with it?

**Comment by albedoweb** [comment]
@rjriel I'm not sure we need similar changes in other languages. I've added changes to Python version to be able to use it as backend for demo app.

**Comment by rjriel** [comment]
that makes sense, but I do like the idea of the users being able to run once and check out all three scenarios without having to change environment variables. I'll review and approve so we can merge right away for your demo app purposes, but I'll create a task so I can line up the other languages

**Review by rjriel — APPROVED** [review]
Looks good

**Review by chetvil — APPROVED** [review]

**Pull request merged**
